In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("hr_dataset.csv")

In [4]:
data.head()

satisfaction  evaluation  number_of_projects  average_montly_hours  \
0          0.38        0.53                   2                   157   
1          0.80        0.86                   5                   262   
2          0.11        0.88                   7                   272   
3          0.72        0.87                   5                   223   
4          0.37        0.52                   2                   159   

   time_spend_company  work_accident  churn  promotion department  salary  
0                   3              0      1          0      sales     low  
1                   6              0      1          0      sales  medium  
2                   4              0      1          0      sales  medium  
3                   5              0      1          0      sales     low  
4                   3              0      1          0      sales     low

In [5]:
data.isna().sum()

satisfaction            0
evaluation              0
number_of_projects      0
average_montly_hours    0
time_spend_company      0
work_accident           0
churn                   0
promotion               0
department              0
salary                  0
dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   satisfaction          14999 non-null  float64
 1   evaluation            14999 non-null  float64
 2   number_of_projects    14999 non-null  int64  
 3   average_montly_hours  14999 non-null  int64  
 4   time_spend_company    14999 non-null  int64  
 5   work_accident         14999 non-null  int64  
 6   churn                 14999 non-null  int64  
 7   promotion             14999 non-null  int64  
 8   department            14999 non-null  object 
 9   salary                14999 non-null  object 
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [7]:
data.describe()

satisfaction    evaluation  number_of_projects  average_montly_hours  \
count  14999.000000  14999.000000        14999.000000          14999.000000   
mean       0.612834      0.716102            3.803054            201.050337   
std        0.248631      0.171169            1.232592             49.943099   
min        0.090000      0.360000            2.000000             96.000000   
25%        0.440000      0.560000            3.000000            156.000000   
50%        0.640000      0.720000            4.000000            200.000000   
75%        0.820000      0.870000            5.000000            245.000000   
max        1.000000      1.000000            7.000000            310.000000   

       time_spend_company  work_accident         churn     promotion  
count        14999.000000   14999.000000  14999.000000  14999.000000  
mean             3.498233       0.144610      0.238083      0.021268  
std              1.460136       0.351719      0.425924      0.144281  
min              2.000000       0.000000      0.000000      0.000000  
25%              3.000000       0.000000      0.000000      0.000000  
50%              3.000000       0.000000      0.000000      0.000000  
75%              4.000000       0.000000      0.000000      0.000000  
max             10.000000       1.000000      1.000000      1.000000

In [8]:
y = data["churn"]

In [9]:
x = data.drop("churn", axis=1)

In [10]:
x

satisfaction  evaluation  number_of_projects  average_montly_hours  \
0              0.38        0.53                   2                   157   
1              0.80        0.86                   5                   262   
2              0.11        0.88                   7                   272   
3              0.72        0.87                   5                   223   
4              0.37        0.52                   2                   159   
...             ...         ...                 ...                   ...   
14994          0.40        0.57                   2                   151   
14995          0.37        0.48                   2                   160   
14996          0.37        0.53                   2                   143   
14997          0.11        0.96                   6                   280   
14998          0.37        0.52                   2                   158   

       time_spend_company  work_accident  promotion department  salary  
0                       3              0          0      sales     low  
1                       6              0          0      sales  medium  
2                       4              0          0      sales  medium  
3                       5              0          0      sales     low  
4                       3              0          0      sales     low  
...                   ...            ...        ...        ...     ...  
14994                   3              0          0    support     low  
14995                   3              0          0    support     low  
14996                   3              0          0    support     low  
14997                   4              0          0    support     low  
14998                   3              0          0    support     low  

[14999 rows x 9 columns]

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [12]:
le.fit(x['salary'])

LabelEncoder()

In [13]:
le.classes_ = np.array(["low","medium","high"])

In [14]:
le.classes_

array(['low', 'medium', 'high'], dtype='<U6')

In [15]:
x

satisfaction  evaluation  number_of_projects  average_montly_hours  \
0              0.38        0.53                   2                   157   
1              0.80        0.86                   5                   262   
2              0.11        0.88                   7                   272   
3              0.72        0.87                   5                   223   
4              0.37        0.52                   2                   159   
...             ...         ...                 ...                   ...   
14994          0.40        0.57                   2                   151   
14995          0.37        0.48                   2                   160   
14996          0.37        0.53                   2                   143   
14997          0.11        0.96                   6                   280   
14998          0.37        0.52                   2                   158   

       time_spend_company  work_accident  promotion department  salary  
0                       3              0          0      sales     low  
1                       6              0          0      sales  medium  
2                       4              0          0      sales  medium  
3                       5              0          0      sales     low  
4                       3              0          0      sales     low  
...                   ...            ...        ...        ...     ...  
14994                   3              0          0    support     low  
14995                   3              0          0    support     low  
14996                   3              0          0    support     low  
14997                   4              0          0    support     low  
14998                   3              0          0    support     low  

[14999 rows x 9 columns]

In [16]:
x = pd.get_dummies(x)

In [17]:
x

satisfaction  evaluation  number_of_projects  average_montly_hours  \
0              0.38        0.53                   2                   157   
1              0.80        0.86                   5                   262   
2              0.11        0.88                   7                   272   
3              0.72        0.87                   5                   223   
4              0.37        0.52                   2                   159   
...             ...         ...                 ...                   ...   
14994          0.40        0.57                   2                   151   
14995          0.37        0.48                   2                   160   
14996          0.37        0.53                   2                   143   
14997          0.11        0.96                   6                   280   
14998          0.37        0.52                   2                   158   

       time_spend_company  work_accident  promotion  department_IT  \
0                       3              0          0              0   
1                       6              0          0              0   
2                       4              0          0              0   
3                       5              0          0              0   
4                       3              0          0              0   
...                   ...            ...        ...            ...   
14994                   3              0          0              0   
14995                   3              0          0              0   
14996                   3              0          0              0   
14997                   4              0          0              0   
14998                   3              0          0              0   

       department_RandD  department_accounting  department_hr  \
0                     0                      0              0   
1                     0                      0              0   
2                     0                      0              0   
3                     0                      0              0   
4                     0                      0              0   
...                 ...                    ...            ...   
14994                 0                      0              0   
14995                 0                      0              0   
14996                 0                      0              0   
14997                 0                      0              0   
14998                 0                      0              0   

       department_management  department_marketing  department_product_mng  \
0                          0                     0                       0   
1                          0                     0                       0   
2                          0                     0                       0   
3                          0                     0                       0   
4                          0                     0                       0   
...                      ...                   ...                     ...   
14994                      0                     0                       0   
14995                      0                     0                       0   
14996                      0                     0                       0   
14997                      0                     0                       0   
14998                      0                     0                       0   

       department_sales  department_support  department_technical  \
0                     1                   0                     0   
1                     1                   0                     0   
2                     1                   0                     0   
3                     1                   0                     0   
4                     1                   0                     0   
...                 ...                 ...                   ...   
14994                 0                 

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x,y,
                                                    test_size=0.2,random_state=32 )

In [20]:
from sklearn.tree import DecisionTreeClassifier

In [21]:
dt = DecisionTreeClassifier()

In [22]:
dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [23]:
y_pred = dt.predict(x_test)

In [24]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [25]:
acc = accuracy_score(y_test, y_pred)

In [26]:
print(acc)

0.9796666666666667


In [27]:
confusion_matrix(y_test, y_pred)

array([[2276,   42],
       [  19,  663]])

In [28]:
from sklearn.ensemble import BaggingClassifier

In [29]:
dt = DecisionTreeClassifier()

In [30]:
bg = BaggingClassifier(estimator = dt, n_estimators= 50)

In [31]:
bg.fit(x_train, y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=50)

In [32]:
y_pred = bg.predict(x_test)

In [33]:
confusion_matrix(y_test, y_pred)

array([[2314,    4],
       [  18,  664]])

In [34]:
accuracy_score(y_test, y_pred)

0.9926666666666667

In [35]:
from sklearn.model_selection import cross_val_score

In [36]:
cross_results = cross_val_score(bg, x, y, cv = 5)

In [37]:
cross_results

array([0.99733333, 0.978     , 0.98233333, 0.99733333, 0.99333111])

In [38]:
cross_results.mean()

0.9896662220740247